### ISSUE TITLE
please add support for MX-Linux

### ISSUE THREAD

**Issue by justTravis** [zocker-160/keyboard-center#51]
MX is based on Debian so it seems like it should work, but it doesn't.  

The error it fails with is that it cannot find the module "package"

**Comment by zocker-160** [comment]
Is that error during installation or when trying to run it?

**Comment by justTravis** [comment]
When trying to run it.  The install seems to go fine.  Running it by double-clicking the icon just seems to "do nothing."  Running "sudo keyboard-center" gives the error I mentioned.

**Comment by justTravis** [comment]
and FYI the same problem happens in LMDE (Linux Mint Debian Edition).

**Comment by zocker-160** [comment]
Would it be possible for you to give me an actual terminal output, because I sadly currently really don't know what `cannot find the module "package"` is supposed to mean since "package" could be anything :(.

I will try to reproduce this later today on LMDE.

**Comment by justTravis** [comment]
Yes.  My apologies.  I've tried now on numerous Debian based distributions (trying to wean myself from Arch based) and all in common have this same error message:

Traceback (most recent call last):
  File "/usr/lib/keyboard-center/main.py", line 8, in <module>
    from mainUi import MainWindow
  File "/usr/lib/keyboard-center/mainUi.py", line 5, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

**Comment by zocker-160** [comment]
ahhh now I understand the issue, thank you.

Will fix asap.

**Comment by zocker-160** [comment]
I pushed a new version, which removes the dependency from packaging.version. Let me know if that works for you.

**Comment by justTravis** [comment]
works for me now!  thanks!!!
